// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn2G3NNaXDgogqks-J5JzdmFNWiToMZyc',
    appId: '1:120481511994:android:1f8def1725fadef0ac9303',
    messagingSenderId: '120481511994',
    projectId: 'dashboard-19a7e',
    storageBucket: 'dashboard-19a7e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwe_D3fXVUPqnqj8-i2qsWWQbjUBPL4ZQ',
    appId: '1:120481511994:web:868947a0be1a37c3ac9303',
    messagingSenderId: '120481511994',
    projectId: 'dashboard-19a7e',
    authDomain: 'dashboard-19a7e.firebaseapp.com',
    storageBucket: 'dashboard-19a7e.firebasestorage.app',
    measurementId: 'G-20K1TZ7L0J',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaAlsZ9nn8BuPf_tDgu-pXVLZk3QCrUnI',
    appId: '1:120481511994:ios:413bf765f358b112ac9303',
    messagingSenderId: '120481511994',
    projectId: 'dashboard-19a7e',
    storageBucket: 'dashboard-19a7e.firebasestorage.app',
    iosBundleId: 'com.example.newSchool',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaAlsZ9nn8BuPf_tDgu-pXVLZk3QCrUnI',
    appId: '1:120481511994:ios:413bf765f358b112ac9303',
    messagingSenderId: '120481511994',
    projectId: 'dashboard-19a7e',
    storageBucket: 'dashboard-19a7e.firebasestorage.app',
    iosBundleId: 'com.example.newSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwe_D3fXVUPqnqj8-i2qsWWQbjUBPL4ZQ',
    appId: '1:120481511994:web:16db4abc68087983ac9303',
    messagingSenderId: '120481511994',
    projectId: 'dashboard-19a7e',
    authDomain: 'dashboard-19a7e.firebaseapp.com',
    storageBucket: 'dashboard-19a7e.firebasestorage.app',
    measurementId: 'G-NNMQL0TWQB',
  );

}